export { default as IndexPage } from "./IndexPage/IndexPage.react"
export { default as InsightsPage } from "./InsightsPage/InsightsPage.react"
export { default as ServicesPage } from "./ServicesPage/ServicesPage.react"
export { default as ProfilePage } from "./ProfilePage/ProfilePage.react"
export { default as NotFoundPage } from "./404Page/404Page.react"
